#!/bin/bash
#
# check and update pimatic alarm configuration
#
# set -x

for incl in . ../lib /usr/local/lib
do
    [ -f $incl/pimatic.incl ] && { source $incl/pimatic.incl ; break ; }
done

ALARM="switch_alarm_system"
CHECK="rule_alarm-check"

# turn off alarm system
pimatic_get /api/device/$ALARM/turnOff >/dev/null || exit
echo # print new line

RULE_STRING=$( pimatic_get /api/rules/$CHECK | jq -r '.rule.string' ) || exit
# rule starts with 'when' since release 0.9
RULE="${RULE_STRING%% pressed*} pressed"
# rule syntax: when TRIGGER and if CONDITION and CONDITON
RULE_AND=${RULE_STRING##*pressed }
RULE_AND=${RULE_AND%% contact_*}
RULE_THEN=${RULE_STRING##* then }

# loop over all *ContactSensor devices
for sensor in $(pimatic_get /api/devices | jq -r '.devices | map(select(.config.class |contains("ContactSensor")))[].id')
do
	case "$sensor" in
		contact_*) # process only contact_ devices
			# state mapping: true => closed, false => opened
			state=$(pimatic_get /api/devices/$sensor | jq -r '.device.attributes | map(select(.name == "contact"))[0].value')
			device=${sensor/contact_/}

			echo $device : $state
			[ "$state" == "true" ] && RULE="$RULE $RULE_AND $sensor is closed"
	        # strip optional 'if' after the first expression
	        RULE_AND=${RULE_AND%% *}
			for prefix in alert locked unlock
			do
				rule="rule_alarm-${prefix}-${device//_/-}"
				pimatic_patch /api/rules/$rule "{\"rule\": {\"active\": \"$state\"}}" >/dev/null || exit
			done
			;;
		*)
			echo $device: skipped
			;;
	esac
done


# mask quoted strings in $RULE_THEN actions
# RULE="$RULE then set \$alarmLocked = 0 and log \\\"Alarm system unlocked!\\\""
RULE="$RULE then $(echo $RULE_THEN | sed 's/"/\\"/g')"
# echo $RULE

# update rule_alarm-check
pimatic_patch /api/rules/$CHECK "{\"rule\": {\"ruleString\": \"$RULE\"}}" >/dev/null || exit

# clear $alarmLocked 
pimatic_patch /api/variables/alarmLocked '{"type": "value", "valueOrExpression": "0"}' >/dev/null || exit

