#!/bin/bash
[ "$1" ] && VAR="$1" || exit
[ "$2" ] && VAL="$2"

# load pimatic library and credentials
[ -f pimatic.incl ] && source pimatic.incl || source /usr/local/lib/pimatic.incl || exit

if [ "$VAL" ]
then
    # RESULT=$(pimatic_patch /api/variables/$VAR "{\"type\": \"value\", \"valueOrExpression\": \"$VAL\"}") || exit
    pimatic_set_variable "$VAR" "$VAL"
else
    #VALUE=$(pimatic_get /api/variables/$VAR | jq -r '.variable.value') || exit
    #[ "$VALUE" == "null"  ] && echo "" || echo $VALUE
    pimatic_get_variable "$VAR"
fi