#!/bin/bash
[ "$1" ] && VAR="$1" || exit

# load pimatic library and credentials
[ -f pimatic.incl ] && source pimatic.incl || source /usr/local/lib/pimatic.incl || exit

VALUE=$(pimatic_get /api/variables/$VAR | jq -r '.variable.value') || exit
[ "$VALUE" == "null"  ] && echo "" || echo VALUE
